#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='code'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='code'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/{,s}bin(N)

  # Homebrew: postgresql@15 is keg-only, which means it was not symlinked into /opt/homebrew,
  # because this is an alternate version of another formula
  /opt/homebrew/opt/postgresql@15/bin

  # Homebrew: openjdk is keg-only, which means it was not symlinked into /opt/homebrew,
  # because macOS provides similar software and installing this software in
  # parallel can cause all kinds of trouble.
  /opt/homebrew/opt/openjdk/bin

  # Pipx
  $HOME/.local/bin

  # Volta
  $VOLTA_HOME/bin

  # Homebrew
  /opt/{homebrew,local}/{,s}bin(N)

  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi
