#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

### pyenv
[[ -d $XDG_DATA_HOME/pyenv ]] && export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

### zoxide
[[ -d $XDG_DATA_HOME ]] && export _ZO_DATA_DIR="$XDG_DATA_HOME/zoxide"

### volta
[[ -d $XDG_DATA_HOME ]] && export VOLTA_HOME="$XDG_DATA_HOME/volta"

### homebrew
# Set Brewfile location.
[[ -d $XDG_CONFIG_HOME ]] && export HOMEBREW_BUNDLE_FILE="$XDG_CONFIG_HOME/homebrew/Brewfile"

# Disable VSCode integration.
export $HOMEBREW_BUNDLE_DUMP_NO_VSCODE=true
