#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Set pyenv root dir
[[ -d $XDG_DATA_HOME/pyenv ]] && export PYENV_ROOT="$XDG_DATA_HOME/pyenv"

# Set nvm dir
[[ -d $XDG_DATA_HOME/nvm ]] && export NVM_DIR="$XDG_DATA_HOME/nvm"